
services:

  db:
    image: postgres:16
    container_name: database
    volumes:
      - C:/containers/database/pontoeletronico/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 3030:5432
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - C:/containers/backend/pontoeletronico/python:/app/data/python
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
  

    
 
  